#use an official Node.js runtime as a parent image
FROM node:10.15.3-alpine

#set the working directory to auth-microservice/src
WORKDIR /auth-microservice/src

#copy the current directory contents into the container at /auth-microservice/src
COPY . /auth-microservice/src

RUN npm install

# Make port 3000 available to the world outside this container
EXPOSE 3001

CMD ["node", "src/app.js"]
