name: Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install Dependencies
      run: npm install
      working-directory: auth-microservice/src/

    - name: Run Lint
      run: npm run lint
      working-directory: auth-microservice/src/
